set_property SRC_FILE_INFO {cfile:/home/jaredmoulton/Programming/Vivado/SevenSegmentImage/SevenSegmentImage.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc rfile:../../../SevenSegmentImage.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  V17 [ get_ports {sw [0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  V16 [ get_ports {sw [1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W16 [ get_ports {sw [2]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W17 [ get_ports {sw [3]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W15 [ get_ports {sw [4]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  V15 [ get_ports {sw [5]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W14 [ get_ports {sw [6]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W13 [ get_ports {sw [7]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W7 [ get_ports {seg [0]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W6 [ get_ports {seg [1]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  U8 [ get_ports {seg [2]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  V8 [ get_ports {seg [3]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  U5 [ get_ports {seg [4]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  V5 [ get_ports {seg [5]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  U7 [ get_ports {seg [6]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U2 [ get_ports {an [0]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  U4 [ get_ports {an [1]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  V4 [ get_ports {an [2]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN  W4 [ get_ports {an [3]}]
